### ISSUE TITLE
Colors for matching symbols

### ISSUE THREAD

**Issue by offero** [prometheux-ar/cyberpunk#83]
The colors for matching symbols don't really fit. See how it's blue on blue on purple?

![image](https://user-images.githubusercontent.com/4681330/68232363-f2977680-ffca-11e9-9d4b-d1e3b62a6cbf.png)

**Comment by max-SS** [comment]
Hello, the reason for putting the selection in that color, is because not only was it the one that, in my opinion, best contrasted with all the other colors of the theme, but also gave the feeling of being the silhouette of a city at night. as in the example image below. 
![Web 1920 – 1](https://user-images.githubusercontent.com/9059596/69916973-305bb380-1440-11ea-9af8-276aa744921d.png)
But if you have any proposals, I might consider them.
